### PR TITLE
Rect: Initial implementation

### PR DESCRIPTION
**Pull request by hoppfrosch**
Hi Tiq,

this pull request isn't intended to be pulled by you but rather a invitation for you to review my code and say whether it meets your desired standards. After answering my questions you should reject this pull-request. I will refactor my sources according your answers before the pull request should be accepted.
Following questions arose during implementing class Rect:

- Is it intended to implement all/most methods a GDI++ class offers? (for example https://msdn.microsoft.com/en-us/library/windows/desktop/ms534495(v=vs.85).aspx)
- There are a couple of GetXXXX Methods in original GDI++. Should they be implemented as methods or (better in my eyes) as properties?
- Should only methods/properties from original GDI++-class be implemented - or are additional methods/properties possible? (For example: xul, yul ("X/Y-upper left corner") xlr,ylr (X/Y lower right corner for class Rect). If not, I'm thinking about implementing derived classes offering the functionality I need ...
- Question more generally: How strict should the original methodset of GDI+-classes be followed? (Implementing all features? Implementing methods as properties? Implementing additional stuff?...)

Now a question concerning AHK-programming technique.
AHK does not strictly allow overloading constructor - you implemented overloading by counting the number of arguments of the constructor.
What to do, if there have to be more than one constructor, having the same count of arguments? (for example: _Rect::Contains(Point&)_ and _Rect::Contains(Rect&)_ - https://msdn.microsoft.com/en-us/library/windows/desktop/ms534495(v=vs.85).aspx)

And last:
I've set up a second repository to host unittests for gdip implementation (using uberi's great YUnit framework (https://github.com/Uberi/Yunit). This repository is hosted at https://github.com/hoppfrosch/Gdip2_Unittests

Cheers 
Hoppfrosch

### CODE REVIEW

**Comment by tariqporter** [comment]
- I don't necessarily intend to implement every sub class and method. Only the ones that add obvious benefit. `Rect` may have use, but will need to be reviewed whether it adds large benefit over `Point` and `Size` (I think it probably does).

- Yes, any simple `Get` methods in my opinion would be better served as properties

- I do not intend to follow the `Gdip`library at all, as can be seen with `Window` and `Bitmap` inheriting from `Drawing` class. The idea is to make them nearly synonymous  so that the same code could be applied to a `Window` or `Bitmap` object.

- As above - Not strict at all. I don't want to follow it as I want it to be as easy to use as possible.

- Yes, I have implemented a lot of overloading (And there are more overloads to add to each constructor still). See [Object.ahk](https://github.com/tariqporter/Gdip2/blob/master/lib/Object.ahk#L14), specifically `if (params[1].__Class = "Gdip.Size")` as to how we can overload with same number of parameters

- Very cool! I had wanted to run unit tests in ahk. Much appreciated. Are these to be run locally? I can very simply add these unit tests to my webpack's package.json, or are they supposed to be run on github similar to travis CI?

**Comment by hoppfrosch** [comment]
- I used to use my own implementation of a Rect within a personal project. As I have to reimplement this, I decided to implement GDIP-Rect functionality - and as I thought it might be useful within an "offical" AHK-GDIP distribution I decided to integrate this within your project. 
As I need some Additional functionality for Rects. I will implement GDIP's RECT-functionality in a class - and will use this class as a baseclass for my specialized needs. Within my class, I will implement properties, caliing the GetXXXX-Methods()

- I haven't reviewed your `Bitmap` and `Drawing` class yet. As you don't reimplement the standard GDIP-functionality - do you use any documentation system to produce a comprehensive documentation?

- Thanky for your hint to constructor overlaoding in `Object.ahk` - I will have a look into it for further insights on overloading in AHK

- At the moment, the unit tests are meant to run locally. I currently see nothing that speaks against using it in an CI system later (maybe an output module has to be written, which provides output which could be understood by the CI-system ...)

**Comment by tariqporter** [comment]
I have created a unit test library as I didn't really love the other one. It was cumbersome and required an external application to debug.

https://github.com/tariqporter/ahk-unit

This one will run tests on any #Include file changing, and has all usual test methods that the other library did not have. I will add this to `Gdip2` tomorrow to show how to use it

**Comment by hoppfrosch** [comment]
> ... and required an external application to debug.

Either that's not correct - or I don't understand what you are saying here (due to my poor english): YUnit offers different Output-modules to select where to log the test results to. The one I used in my example was [DebugView++](https://github.com/djeedjay/DebugViewPP) (as I mostly use `OutputDebug` for AHK-debugging) Other output-modules are Window, StdOut and a JUnit compatible XML-file. More output modules could be added easily . You even could log to multiple modules at once. (see https://github.com/Uberi/Yunit/blob/master/doc/Main.md)

What I personally like with YUnit is writing test classes (each TestSuite is a class on its own ...)

> ... and has all usual test methods that the other library did not have

Having only `Assert()` as test method, is not a drawback in my eyes, as I'm always able to do fancy comparisons before calling `assert()` - using `assert()` only to check whether the previous comparison was true or false. It's simply a matter of taste. ;-)

**Comment by tariqporter** [comment]
Ah, I hadn't seen that you could change to stdout. I have added ahk-unit as the test library. It is very easy to setup, and will re-run all tests on any included file changing. Just need to run `npm test` from console

**Comment by hoppfrosch** [comment]
Closed as new pull request will be made concernig Rect

**Pull request closed without merging**
